apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f example-voting-app-master/docker-compose.yml
    kompose.version: 1.2.0 (99f88ef)
  creationTimestamp: null
  labels:
    io.kompose.service: db
  name: db
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    io.kompose.service: db
status:
  loadBalancer: {}
