apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f example-voting-app-master/docker-compose.yml
    kompose.version: 1.2.0 (99f88ef)
  creationTimestamp: null
  labels:
    io.kompose.service: result
  name: result
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: result
    spec:
      containers:
      - image: tgscloudevops.azurecr.io/result
        name: result
        ports:
        - containerPort: 8080
        - containerPort: 5858
        resources: {}
      restartPolicy: Always
status: {}
