apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f example-voting-app-master/docker-compose.yml
    kompose.version: 1.2.0 (99f88ef)
  creationTimestamp: null
  labels:
    io.kompose.service: result
  name: result
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  - name: "5858"
    port: 5858
    targetPort: 5858
  selector:
    io.kompose.service: result
status:
  loadBalancer: {}
